version: "3"
services:
  application:
    image: spring-boot-mysql-app
    ports:
      - "8080:8080"
    networks:
      - springboot-db-net
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app
    
  mysqldb:
    image: mysql:latest
    networks:
      - springboot-db-net
    environment:
      - MYSQL_ROOT_PASSWORD=admin1234
      - MYSQL_DATABASE=sivadb
    volumes:
      - /data/mysql
networks:
  springboot-db-net:
